### PR TITLE
Toolbox generator

### PR DESCRIPTION
**Pull request by noxyyk**

### CODE REVIEW

**Review by inventionpro — APPROVED** [review]
approve
(don't really like it being automatic)

**Comment by noxyyk** [comment]
> approve
> (don't really like it being automatic)

@inventionpro it`s not fully automatic, you can specify weight so it will define what is first, and this is much better than defining it twice I believe

**Comment by inventionpro** [comment]
Still missing labels, shadow blocks and prob more stuff

**Comment by noxyyk** [comment]
I will do that tmrw

**Review by ItsLimeNade — APPROVED** [review]
lgtm (didn't read it)

**Pull request merged**
