### PR TITLE
mutator support added

### PR DESCRIPTION
**Pull request by mrredo**
in here you can see how to define a block with a mutator
https://github.com/Dis-codes/workspace/blob/272552d6dbca57ca0427b1e2a410f802c36f4e7c/app/src/lib/blocks/js/test/test.ts#L26-L45
but you can also use custom blocks as a base
```js
{
    //...blockdefinition
    mutationData: {
        "blockType": "block_id",
        //....mutator data
    },
}
```
and in here you can see how to handle it as arguments

https://github.com/Dis-codes/workspace/blob/272552d6dbca57ca0427b1e2a410f802c36f4e7c/app/src/lib/blocks/js/test/test.ts#L114-L116

### CODE REVIEW

**Review by mrredo — COMMENTED** [review]
looks good but another person need to review

**Comment by noxyyk** [comment]
@mrredo It looks good, but I want to ask if the "mutator" is required or if you could replace it rather than mutatorData, and if it´s possible to use it as object than array like the arguments so it will be the same, if not it´s ok.

**Comment by mrredo** [comment]
> @mrredo It looks good, but I want to ask if the "mutator" is required or if you could replace it rather than mutatorData, and if it´s possible to use it as object than array like the arguments so it will be the same, if not it´s ok.
So make the mutator an object then inside that object place the mutator name?

**Comment by mrredo** [comment]
Dont merge another bug found!
When you add 2 mutator blocks and for example for one title is enabled and for other description it will
synchronize and lose configuration.

**Pull request closed without merging**
