### PR TITLE
Small mutator update: branches added for checkbox mutator

### PR DESCRIPTION
**Pull request by mrredo**
to add branch
just in the inputs list add for the input you want `branch: true`

### CODE REVIEW

**Review by noxyyk — CHANGES_REQUESTED** [review]
@mrredo can you move MutatorType into blockregistry tool?

**Comment by mrredo** [comment]
> @mrredo can you move MutatorType into blockregistry tool?

I cant do that since im using mutatorType in utils/mutators.ts
and in blockRegistryTool.ts im importing mutators.ts and i if i add MutatorType to mutators then its going to import loop.

**Comment by noxyyk** [comment]
Btw you want me to merge this or not yet

**Comment by mrredo** [comment]
Yea please do

**Review by noxyyk — APPROVED** [review]

**Pull request merged**
